name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the image
        run: ./build base-nginx
      - uses: actions/upload-artifact@v3
        with:
          name: my-linux-image
          path: .build/
